### ISSUE TITLE
Implement OIDCMiddlewareClient

### ISSUE THREAD

**Issue by veebkolm** [codemowers/oidc-gateway#10]
```
---
apiVersion: codemowers.io/v1alpha1
kind: OIDCMiddlewareClient
metadata:
  name: prom
spec:
  hostname: %(name)s.codemowers.eu
  allowedGroups:
    - github.com:codemowers:admins
  headerMapping:
    email: Remote-User
  
```
